# This file was generated by GoReleaser. DO NOT EDIT.
cask "lockbox" do
  version "2.0.2"

  on_macos do
    on_intel do
      sha256 "594261dc9a8594cdcf129bda214545519a33aa1731b762ebd3796a4716e4eb94"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "572e9ba08a623d64fbace3d2e0017406732c8b8f1b798ef9e0b798cbee5b8f5a"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0823371d315a82cba5842746248650b7aa433857e583bfc6081a01e5eedf2fe"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c3b2f091c20cc8fc7464ea6ff2e54537c0c9e7887f76dfae232bdc32649ec5e"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lockbox"
  desc "Simple, secure cross-platform CLI password manager"
  homepage "https://github.com/triforge0/lockbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lockbox"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lockbox"]
    end
  end

  # No zap stanza required

end
