# This file was generated by GoReleaser. DO NOT EDIT.
cask "lockbox" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "003dde9da86b66771e7827545cf5912b5ef33ea6e578262cf18bf5328f7f9b45"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d44a55b4f029899633658d5e9f4a5a9f1dff721c21679dfcd352b93b76480d6"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0175f10bce09d49c0997f4111643127b7fc73792a3e7fa6d6b81220605472f8e"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e280e910ba910240783551a7260fc7f43b7a050758de191d5c4c24d2cbb32f5"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lockbox"
  desc "Simple, secure cross-platform CLI password manager"
  homepage "https://github.com/triforge0/lockbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lockbox"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lockbox"]
    end
  end

  # No zap stanza required

end
