# This file was generated by GoReleaser. DO NOT EDIT.
cask "lockbox" do
  version "2.2.0"

  on_macos do
    on_intel do
      sha256 "4e253cf4393ab185cbaff576fcb3507b83ab6a91b7b17d9c042a0358a7aaed0f"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e7c6abef0c9a96e04f8a29a5eb4aff0b79ab5abfb6ec343d5529731c3531a2fb"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a1cc4a9e8dabaa18158454224b2a04139c4ef085b240ae4c255068f396ab9d48"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a87c74f3c1ffc57fd7a20a08b73a6e2da2edfcde1eee70013163ea2eaa29fec"
      url "https://github.com/triforge0/lockbox/releases/download/v#{version}/lockbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lockbox"
  desc "Simple, secure cross-platform CLI password manager"
  homepage "https://github.com/triforge0/lockbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lockbox"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lockbox"]
    end
  end

  # No zap stanza required

end
